# Generated by Django 6.0.4 on 2026-04-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Confirmed')), fields=('doctor', 'date', 'time_slot'), name='unique_confirmed_slot'),
        ),
    ]
